site_name: vs.templ
repo_url: https://github.com/lazy-eggplant/vs-templ
site_dir: dist/website/docs
docs_dir: docs

theme:
  name: readthedocs
  custom_dir: ./
  logo:
markdown_extensions:
  - admonition
  - pymdownx.tilde
  - pymdownx.tasklist
  - sane_lists
  - smarty
  - toc:
      permalink: "#"
plugins:
  - search
  - gh-admonitions
